### ISSUE TITLE
Consider using babel-node

### ISSUE THREAD

**Issue by xjamundx** [cowboy/babel-runtime-wtf#1]
This seems to report the correct line number though I agree the stack track is still not correct :-/:

```
~/dev/test $ babel-node explode.js
/Users/jamuferguson/dev/test/explode.js:1
(function (exports, require, module, __filename, __dirname) { var x = y;
                                                                      ^
ReferenceError: y is not defined
    at Object.<anonymous> (explode.js:1:11)
```

**Comment by cowboy** [comment]
Yeah, I really want it to say:

```
/private/tmp/test/index.js:1
let x = y
        ^

ReferenceError: y is not defined
    at Object.<anonymous> (index.js:1:9)
...
```
